name: 'Azure Container Apps Build and Deploy'
on: 
  pull_request:
    branches: [ main ]
  permissions:
    id-token: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          acrName: nsPrdAcrOnline
          containerAppName: tst-ns-prd-aca-online
          resourceGroup: TST-ns-rg-Prd
          imageToBuild:nsprdacronline-d5ghbgbcb3d9ateb.azurecr.io/testubuntu: ${{ github.run_id }}.${{ github.run_attempt }}
